### ISSUE TITLE
[feature request] Highlights for character-level diffing

### ISSUE THREAD

**Issue by lazytype** [mitsuhiko/similar-asserts#1]
See https://github.com/colin-kiegel/rust-pretty-assertions for a reference of what this might look like. Note how only the non-matching characters are bolded and the use of background color.

**Comment by mitsuhiko** [comment]
I'm currently playing around with some heuristics about this. There are cases where one wants character level diffs but there are also situations where this (without semantic cleanups) gets really hard to read.

I opened an issue in similar itself which implements the logic this crate uses.
