### ISSUE TITLE
Expose `Diff` and/or a way to generate it outside of `assrt*` macros

### ISSUE THREAD

**Issue by elliot-u410** [mitsuhiko/similar-asserts#2]
I really like this tool but I don't want to use it for *tests* per-se. I want to actually use it for diffs! Can the functionality be exported in such a way that I don't have to get a `panic` when things fail? `Diff` could be an exposed, opaque type with the `Display` impl.

**Comment by mitsuhiko** [comment]
This might be something worth adding to `similar` itself potentially.

**Comment by mitsuhiko** [comment]
This is exposed now as `SimpleDiff`.
