### ISSUE TITLE
Show only different part instead of the whole thing

### ISSUE THREAD

**Issue by Logarithmus** [mitsuhiko/similar-asserts#5]
When diffing 2 big objects which have a small difference in the middle, it's very hard to know what exactly gone wrong. I have to either scroll the terminal, or to redirect `cargo test` to a file and then use less.

So it would be nice to only display the difference, like diff tool does.

If you don't want to have a breaking change, than you can add a dedicated macro `assert_eq_diff` to display only diff.

**Comment by mitsuhiko** [comment]
It already does that, but it has a pretty long context of 5. I lowered the context to 4 now which makes it kick in slightly earlier.
